services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "invoicer_app"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOTENBERG_URL=http://gotenberg:3000
    networks:
      - default
      - traefik_network
    volumes:
      - "billing_data:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoicer-app.rule=Host(`${HOST}`)"
      - "traefik.http.routers.invoicer-app.entrypoints=websecure"
      - "traefik.http.routers.invoicer-app.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-myresolver}"
      - "traefik.http.services.invoicer-app.loadbalancer.server.port=3000"

  gotenberg:
    image: "gotenberg/gotenberg:8"
    container_name: "invoicer_gotenberg"
    restart: unless-stopped
    networks:
      - default

networks:
  traefik_network:
    external: true
    name: ${TRAEFIK_NETWORK}

volumes:
  billing_data: